//package Model;
//
//public class Rating {
//
//    //The id for the movie rating
//    public int rating_id;
//
//    //The rating number
//    public int rating;
//
//    public int movie_id;
//
//    public Rating(){
//
//    }
//
//    public Rating(int movie_id, int rating){
//        this.movie_id = movie_id;
//        this.rating = rating;
//    }
//
//    public int getMovie_id() {
//        return movie_id;
//    }
//
//    public void setMovie_id(int movie_id) {
//        this.movie_id = movie_id;
//    }
//
//    public int getRating() {
//        return rating;
//    }
//
//    public void setRating(int rating) {
//        this.rating = rating;
//    }
//
//    @Override
//    public boolean equals(Object o) {
//        if (this == o) return true;
//        if (o == null || getClass() != o.getClass()) return false;
//        Rating rating = (Rating) o;
//        return rating_id == rating.rating_id && movie_id == rating.movie_id && rating.equals(rating.rating);
//    }
//    /**
//     * A toString method in the event that you want to test your methods using System.out.println.
//     * This was auto-generated by the IDE (alt+insert).
//     * @return a String representation of this rating.
//     */
//    @Override
//    public String toString() {
//        return "Rating{" +
//                "rating_id=" + rating_id +
//                ", movie_id=" + movie_id +
//                ", rating=" + rating +
//                '}';
//    }
//}
